package org.orange.wechatcontainer.pojo;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.orange.wechatcontainer.common.BaseEntity;


public class AdminInfo extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container_admin_info.adminid
     *
     * @mbggenerated
     */
    private String adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container_admin_info.adminname
     *
     * @mbggenerated
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container_admin_info.loginname
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container_admin_info.loginpwd
     *
     * @mbggenerated
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column container_admin_info.tentantid
     *
     * @mbggenerated
     */
    private String tentantid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container_admin_info.adminid
     *
     * @return the value of container_admin_info.adminid
     *
     * @mbggenerated
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container_admin_info.adminid
     *
     * @param adminid the value for container_admin_info.adminid
     *
     * @mbggenerated
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container_admin_info.adminname
     *
     * @return the value of container_admin_info.adminname
     *
     * @mbggenerated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container_admin_info.adminname
     *
     * @param adminname the value for container_admin_info.adminname
     *
     * @mbggenerated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container_admin_info.loginname
     *
     * @return the value of container_admin_info.loginname
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container_admin_info.loginname
     *
     * @param loginname the value for container_admin_info.loginname
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container_admin_info.loginpwd
     *
     * @return the value of container_admin_info.loginpwd
     *
     * @mbggenerated
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container_admin_info.loginpwd
     *
     * @param loginpwd the value for container_admin_info.loginpwd
     *
     * @mbggenerated
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column container_admin_info.tentantid
     *
     * @return the value of container_admin_info.tentantid
     *
     * @mbggenerated
     */
    public String getTentantid() {
        return tentantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column container_admin_info.tentantid
     *
     * @param tentantid the value for container_admin_info.tentantid
     *
     * @mbggenerated
     */
    public void setTentantid(String tentantid) {
        this.tentantid = tentantid == null ? null : tentantid.trim();
    }
    
    public int hashCode() {
		return new HashCodeBuilder()
			.append(getAdminid())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof AdminInfo == false) return false;
		if(this == obj) return true;
		AdminInfo other = (AdminInfo)obj;
		return new EqualsBuilder()
			.append(getAdminid(),other.getAdminid())
			.isEquals();
	}
    
}