package org.orange.wechatcontainer.pojo;

import java.util.List;

import javax.validation.constraints.Max;
import javax.validation.constraints.Past;

import org.orange.wechatcontainer.common.BaseEntity;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;


import org.orange.wechatcontainer.util.DateConvertUtils;

public class CardTypeInfo extends BaseEntity implements java.io.Serializable{
	private static final long serialVersionUID = 5454155825314635342L;
	
	//alias
	public static final String TABLE_ALIAS = "member_cardtype_info";
	
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_cardtype_info.cardtypeid
     *
     * @mbggenerated
     */
    private String cardtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_cardtype_info.cardtypename
     *
     * @mbggenerated
     */
    private String cardtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_cardtype_info.cardtypeleve
     *
     * @mbggenerated
     */
    private Integer cardtypeleve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_cardtype_info.cardtypepic
     *
     * @mbggenerated
     */
    private String cardtypepic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_cardtype_info.tentantid
     *
     * @mbggenerated
     */
    private String tentantid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_cardtype_info.cardtypeid
     *
     * @return the value of member_cardtype_info.cardtypeid
     *
     * @mbggenerated
     */
    public String getCardtypeid() {
        return cardtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_cardtype_info.cardtypeid
     *
     * @param cardtypeid the value for member_cardtype_info.cardtypeid
     *
     * @mbggenerated
     */
    public void setCardtypeid(String cardtypeid) {
        this.cardtypeid = cardtypeid == null ? null : cardtypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_cardtype_info.cardtypename
     *
     * @return the value of member_cardtype_info.cardtypename
     *
     * @mbggenerated
     */
    public String getCardtypename() {
        return cardtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_cardtype_info.cardtypename
     *
     * @param cardtypename the value for member_cardtype_info.cardtypename
     *
     * @mbggenerated
     */
    public void setCardtypename(String cardtypename) {
        this.cardtypename = cardtypename == null ? null : cardtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_cardtype_info.cardtypeleve
     *
     * @return the value of member_cardtype_info.cardtypeleve
     *
     * @mbggenerated
     */
    public Integer getCardtypeleve() {
        return cardtypeleve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_cardtype_info.cardtypeleve
     *
     * @param cardtypeleve the value for member_cardtype_info.cardtypeleve
     *
     * @mbggenerated
     */
    public void setCardtypeleve(Integer cardtypeleve) {
        this.cardtypeleve = cardtypeleve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_cardtype_info.cardtypepic
     *
     * @return the value of member_cardtype_info.cardtypepic
     *
     * @mbggenerated
     */
    public String getCardtypepic() {
        return cardtypepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_cardtype_info.cardtypepic
     *
     * @param cardtypepic the value for member_cardtype_info.cardtypepic
     *
     * @mbggenerated
     */
    public void setCardtypepic(String cardtypepic) {
        this.cardtypepic = cardtypepic == null ? null : cardtypepic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_cardtype_info.tentantid
     *
     * @return the value of member_cardtype_info.tentantid
     *
     * @mbggenerated
     */
    public String getTentantid() {
        return tentantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_cardtype_info.tentantid
     *
     * @param tentantid the value for member_cardtype_info.tentantid
     *
     * @mbggenerated
     */
    public void setTentantid(String tentantid) {
        this.tentantid = tentantid == null ? null : tentantid.trim();
    }

	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getCardtypeid())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj instanceof CardTypeInfo == false) return false;
		if(this == obj) return true;
		CardTypeInfo other = (CardTypeInfo)obj;
		return new EqualsBuilder()
			.append(getCardtypeid(),other.getCardtypeid())
			.isEquals();
	}

	}
